### ISSUE TITLE
Circular relation error

### ISSUE THREAD

**Issue by mikenavi** [mancku/strapi-plugin-schemas-to-ts#1]
Hello,

If scheme have relation to itself (for example organization with suborganization implements one model with parent-child fields relation) got error on importing type

**Comment by mancku** [comment]
Sorry @mikenavi I've been busy and didn't have time to take a look to this. I'll work on it next week. I'm pretty sure it'll be an easy fix

**Comment by mancku** [comment]
Hi @mikenavi I just published the version 1.1.1 to NPM with this fix

**Comment by mancku** [comment]
Hi @mikenavi I just published the version 1.1.1 to NPM with this fix

**Comment by mikenavi** [comment]
Thank you very much
