### ISSUE TITLE
This plugin vs Strapi's ts:generate-types

### ISSUE THREAD

**Issue by kalnode** [mancku/strapi-plugin-schemas-to-ts#2]
I'm trying to understand the relationship of this plugin vs vanilla Strapi v4.

Does this plugin provide any other benefit other than automatically generating types?

For a simple project, where manual type generation is fine, is there anything wrong with simply using Strapi's `ts:generate-types` CLI command?

https://docs.strapi.io/dev-docs/typescript#generate-typings-for-project-schemas

There's also this note, in the docs:

_Types can be automatically generated on server restart by adding `autogenerate: true` to [the config/typescript.js|ts configuration file](https://docs.strapi.io/dev-docs/configurations/typescript#strapi-specific-configuration-for-typescript)._

**Comment by SeedyROM** [comment]
From what I can see, the `strapi` generated types are for internal systems. A big thing I can instantly see is that content type  attributes are missing important fields. And they're also excessively complex, go look at a content type def.

This tool seems more for people consuming the Apis via REST, which is my current use case.

**Comment by mancku** [comment]
Hi @kalnode sorry for taking so long in getting back to you. 
As @SeedyROM said, strapi generated types are for internal systems. The idea behind this plugin is to have types that can be used while developing, so every content type has it's typescript interface that you can use in your code.

**Comment by kalnode** [comment]
These responses are super helpful!

For my context, I have Strapi feeding multiple front-ends (like white-labelled apps). Certainly I have API documentation happening but it's much more effective to just update typings in Strapi, then have those types automatically be available in external repo's.

Aspects:

**1. Generate types**
Use this plugin, presumably

**2. Distribute types**
Unknown, but probably involves a git sub-module?
I have a huge amount of post types and on-going changes. Copy-pasting updates seems silly.

**Comment by mancku** [comment]
Hi @kalnode I'm glad we could be of help!

For the distribution, let me know if you can't manage it with a sub-module, so I look for a solution.
When I began working on this project, I thought about making the path where the interfaces are placed to be totally configurable, but then I discarded the idea to be able to keep the plugin more simple. Maybe making the path totally configurable as I initially intended would be a solution, too

**Comment by SeedyROM** [comment]
@mancku I would love having the output be configurable! I'm currently using a local node module to import the types into my Next app, I have a `contentTypes.ts` that re-exports each type from the api code.

**Comment by mancku** [comment]
Hi @SeedyROM so, what you'd like is the output path to be configurable so you could place the files even outside the workspace?

**Comment by SeedyROM** [comment]
No just so they're not as nested in the strapi source. For instance something like `src/types/contentTypes.ts`? Or you could make content types a folder and have each content type be it's own module.

**Comment by mancku** [comment]
@SeedyROM Personally, I'd rather do the folder and then separated files thing. Maybe even a subfolder for content types, another one for components and finally one for the common content types. I think that would help in large projects and maybe that's the reason why putting everything in a single file didn't occurred to me before, but I think both options are valid, so I'll try to implement both of them.

I'm also thinking that if someone changes the paths in their configuration, files would be created in a different place, but the old ones would remain, and they can be tedious to manually delete. The solution could be to delete all .ts files with '`// Interface automatically generated by schemas-to-ts`' in the first lines and delete the ones that aren't being generated in that moment.

**Comment by mancku** [comment]
Hi @SeedyROM, @kalnode I'll close this issue as the conversation evolved to a different point. I've open the issue #22 to add the destination folder feature, though.

**Comment by mancku** [comment]
Hi @SeedyROM @kalnode I finally could work on the #22 one. It has been done in #50 and published in version 1.3.0. Also, the ability to delete files was published in 1.2.0
