### ISSUE TITLE
Add a configuration value to be able to select the generated files folder

### ISSUE THREAD

**Issue by mancku** [mancku/strapi-plugin-schemas-to-ts#22]
As stated in this comment https://github.com/mancku/strapi-plugin-schemas-to-ts/issues/2#issuecomment-1627927427 by @SeedyROM
And also in this one https://github.com/mancku/strapi-plugin-schemas-to-ts/issues/2#issuecomment-1629824580 and this one https://github.com/mancku/strapi-plugin-schemas-to-ts/issues/2#issuecomment-1630442193

The idea would be to be able to select the destination folder for the generated files. Also, to be able to choose between all files in the same folder and separating the files in different folders (API, Common, Components)

Finally, this change would involve deleting the generated files that are in a different path than the selected. That's because if the path is modified, old files would remain in the previous path, and that would be confusing. To do that, the solution could be to delete all .ts files with `// Interface automatically generated by schemas-to-ts` in their first line and delete the ones that aren't being generated in that moment.

**Comment by matepaiva** [comment]
I like the idea of deleting it searching for the comment

**Comment by kandabi-magnificode** [comment]
This would be a great feature and the only thing missing from using this package.

**Comment by gregg-cbs** [comment]
I like the idea of all the types in one folder as we use a monorepo. We can then copy that folder into our other projects using a script we have.

**Comment by gregg-cbs** [comment]
Epic has this been merged and released?

**Comment by mancku** [comment]
@matepaiva @kandabi-magnificode @gregg-cbs It has been done in https://github.com/mancku/strapi-plugin-schemas-to-ts/pull/50 and published in version 1.3.0
