### ISSUE TITLE
Unexpected token when exporting enum

### ISSUE THREAD

**Issue by BayBreezy** [mancku/strapi-plugin-schemas-to-ts#25]
Hello,

Thank you for creating this plugin. I just learned about it today. 
I installed with yarn and enabled it in my plugins.ts file. When I try to start my strapi app, It created a few of the files inside the `content-types` folder of each of my collections. 
Halfway through the process, I get this error below:

```bash
SyntaxError: Unexpected token, expected "{" (9:8)
   7 | import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';
   8 |
>  9 | export enum TimeOfDay {
     |        ^
  10 |   Am = 'AM',
  11 |   Pm = 'PM',}
  12 |
```

It pointed to this location `\node_modules\strapi-plugin-schemas-to-ts\dist\server\schemas-to-ts\converter.js:133:61`.

Any idea of what I need to change to get this to work?

**Comment by BayBreezy** [comment]
Hey @mancku , sure thing

- Node version: 16.20.0
- Strapi version: 4.12.0
- Plugin version: 1.1.9

Schema:

```json
{
  "kind": "collectionType",
  "collectionName": "loan_informations",
  "info": {
    "singularName": "loan-information",
    "pluralName": "loan-informations",
    "displayName": "Loan Information",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "loanAmount": {
      "type": "decimal",
      "required": true
    },
    "loanPurpose": {
      "type": "string",
      "required": true,
      "minLength": 2
    },
    "contactTime": {
      "type": "integer",
      "required": true,
      "min": 1,
      "max": 12
    },
    "timeOfDay": {
      "type": "enumeration",
      "enum": [
        "AM",
        "PM"
      ],
      "required": true
    },
    "loanApplication": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::loan-application.loan-application",
      "mappedBy": "loanInformation"
    },
    "auditLogs": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::audit-log.audit-log",
      "mappedBy": "loanInformation"
    }
  }
}
```

The `timeOfDay` enum is also being used in another schema. Maybe that is causing the issue? The same enum is being exported/created twice?

**Comment by mancku** [comment]
Hi @BayBreezy it is not a problem to have the same enum in different schemas, because it will be created (and exported) in different files. You just need to bear it in mind when importing them, to make sure you're importing the right one.

I'm using node 16.13.0, Strapi 4.12.1 and the version 1.1.9 of the plugin. I created the 3 content types needed to replicate your schema and also added the timeOfDay enum to a different 4th schema, and it worked like a charm, so I couldn't replicate your error 😔

I also took a look at the line 133 of converter.js and the error you're showing me is really weird at this point. Could you confirm that the line 133 of that file in your node_modules is this one?
> const interfacesFileContent = this.interfaceBuilder.buildInterfacesFileContent(schema);

Here's my `loan-information.ts` file for reference:
```ts
// Interface automatically generated by schemas-to-ts

import { LoanApplication } from '../../../loan-application/content-types/loan-application/loan-application';
import { AuditLog } from '../../../audit-log/content-types/audit-log/audit-log';
import { LoanApplication_Plain } from '../../../loan-application/content-types/loan-application/loan-application';
import { AuditLog_Plain } from '../../../audit-log/content-types/audit-log/audit-log';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum TimeOfDay {
  Am = 'AM',
  Pm = 'PM',
}

export interface LoanInformation {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    loanAmount: number;
    loanPurpose: string;
    contactTime: number;
    timeOfDay: TimeOfDay;
    loanApplication?: { data: LoanApplication };
    auditLogs: { data: AuditLog[] };
  };
}
export interface LoanInformation_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  loanAmount: number;
  loanPurpose: string;
  contactTime: number;
  timeOfDay: TimeOfDay;
  loanApplication?: LoanApplication_Plain;
  auditLogs: AuditLog_Plain[];
}

export interface LoanInformation_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  loanAmount: number;
  loanPurpose: string;
  contactTime: number;
  timeOfDay: TimeOfDay;
  loanApplication?: number;
  auditLogs: number[];
}

export interface LoanInformation_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  loanAmount: number;
  loanPurpose: string;
  contactTime: number;
  timeOfDay: TimeOfDay;
  loanApplication?: AdminPanelRelationPropertyModification<LoanApplication_Plain>;
  auditLogs: AdminPanelRelationPropertyModification<AuditLog_Plain>[];
}

```

**Comment by BayBreezy** [comment]
I can confirm that line 133 is the same inside node_modules.
I also keep getting this in the terminal for each file that it writes to 
`No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.`

Maybe it's just how this project is configured. I will create a fresh instance and try it out  then let you know
Also, I am on windows 10(not sure if this may be an issue)

**Comment by BayBreezy** [comment]
@mancku So I tried with a new Strapi app & everthing worked as expected. I created the same enum across different collections just to test & they all got generated and imported properly.
I am not sure what in the other project is triggering the error.
I got the right logs from the plugin in the terminal(the warning I mentioned before did not show up again)

So idk.. i cant replicate it on a new project either. I guess we can close this one then.

**Comment by mancku** [comment]
Hi @BayBreezy thanks for letting me know that it worked out for you.

The babel & parser error makes me think that it might have something to do with prettier 🤔. If prettier has been detected in your project, the file would be formatted before being written to disk. You can see it in this line: https://github.com/mancku/strapi-plugin-schemas-to-ts/blob/1003bacea004a23615d839ed5cfee7d7e0c61769/server/schemas-to-ts/interfaceBuilder.ts#L55

Do you reckon there's some configuration in that project that might be affecting that?
It'd be useful to know.

**Comment by BayBreezy** [comment]
Hello @mancku , You are correct! I removed my `.prettierrc` config file and it worked! 
How do I config prettier to make it work with this plugin? I tried using different prettier file formats but that didn't help.
The only thing that worked was removing the prettier config. Even adding the prettier config to the `package.json` file caused the error to come up lolol.

I also tried removing the `.editorconfig` file & keep the prettier config, but that did not help. The rest of the error logs are pointing to `node_modules\prettier\parser-babel.js:22:1054`

**Comment by mancku** [comment]
Hi @BayBreezy that's weird.
Here are my configuration files on a project I'm using the plugin with prettier involved and it's working just fine. Hope it helps you find which bit of configuration is causing problems:

#### .editorconfig
```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[{package.json,*.yml}]
indent_style = space
indent_size = 2

[*.md]
trim_trailing_whitespace = false
```

#### .eslintrc.js
```js
module.exports = {
    parser: '@typescript-eslint/parser',
    parserOptions: {
      project: 'tsconfig.json',
      tsconfigRootDir : __dirname, 
      sourceType: 'module',
    },
    plugins: ['@typescript-eslint/eslint-plugin'],
    extends: [
      'plugin:@typescript-eslint/recommended',
      'plugin:prettier/recommended',
    ],
    root: true,
    env: {
      node: true,
      jest: true,
    },
    ignorePatterns: ['.eslintrc.js'],
    rules: {
      '@typescript-eslint/interface-name-prefix': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  };
```

#### .prettierrc
```json
{
  "arrowParens": "avoid",
  "bracketSameLine": true,
  "bracketSpacing": true,
  "embeddedLanguageFormatting": "auto",
  "insertPragma": false,
  "parser": "typescript",
  "printWidth": 120,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleAttributePerLine": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false
}
```

#### tsconfig.json
```json
{
  "extends": "@strapi/typescript-utils/tsconfigs/server",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": ".",
    "sourceMap": true,
    "lib": [
      "ES2021"
    ]
  },
  "include": [
    "./",
    "./**/*.ts",
    "./**/*.js",
    "src/**/*.json",
    ".eslintrc.js"
  ],
  "exclude": [
    "node_modules/",
    "build/",
    "dist/",
    ".cache/",
    ".tmp/",
    "src/admin/",
    "**/*.test.*",
    "src/plugins/**"
  ]
}
```

**Comment by BayBreezy** [comment]
Hey @mancku , I think something is wrong with that one project of mine. I tried creating another project, added the prettier config and got no error. I am unable to reproduce the error in any other strapi app of mine

**Comment by jelmer-visser** [comment]
@BayBreezy I had the same issue. Adding `"parser": "babel-ts"` to my `.prettierrc` fixed the error.

**Comment by jelmer-visser** [comment]
@BayBreezy never mind, with this option specified my own formatter is not working anymore.

**Comment by mancku** [comment]
Hi @jelmer-visser thanks for the information.

I hope we both can understand how to reproduce it so it can be fixed.
First, If you try to use the same prettier & babel configuration on a new project, do you experience the same error or as it happened to @BayBreezy you can not reproduce it in a different project?

**Comment by jelmer-visser** [comment]
@mancku I see that you have specified `"parser": "typescript",` in your `.prettierrc`. If I put that inside my `.prettierrc` file it works. But when I run `prettier --write ./` it's also trying to format json files as typescript files. I think that's the issue.

**Comment by mancku** [comment]
Hi @jelmer-visser I think there could be two different (and not mutually exclusive) solutions for that:
1. I could create a config option so everyone can decide whether or not to use prettier in each project.
2. You can add a [.prettierignore](https://prettier.io/docs/en/ignore) file to your project so it'll ignore the json files, if you'd rather not have prettier working on those files.

Unfortunately that doesn't answer why prettier is crashing in some cases, but at lease offers workarounds

**Comment by jelmer-visser** [comment]
@mancku I think option 1 works for me. My project will take care of the formatting itself.

**Comment by mancku** [comment]
@jelmer-visser @BayBreezy I completely agree with you both. I'll try to get it done by tomorrow

**Comment by BayBreezy** [comment]
Hello @mancku . Were you ablee to implement the fix? I am still getting this error when I add a prettier config and use enums

**Comment by Justin-van-der-Velden** [comment]
Hello,

Any update on this issue?
I'm experiencing the same.

**Comment by mancku** [comment]
Hi @BayBreezy @Justin-van-der-Velden sorry I didn't get back to you earlier. In version 1.1.20 I added a configuration option so the plugin would not use prettier on the generated interfaces

**Comment by BayBreezy** [comment]
Hey @mancku Thank you. I saw the update the other day. I have not gotten a chance to check it out yet. Once I do, I will let you know how it goes
