### ISSUE TITLE
strapi 4.14 - change source folder

### ISSUE THREAD

**Issue by win-ru** [mancku/strapi-plugin-schemas-to-ts#28]
Latest strapi version has change files location

>src/common/schemas-to-ts/BeforeRunEvent.ts:3:23 - error TS2307: Cannot find module '@strapi/database/**lib**/lifecycles/index' or its corresponding type declarations.

import { Event } from '@strapi/database/**dist**/lifecycles/index';

**Comment by BayBreezy** [comment]
I was just about to come post this here. Thanks @win-ru @mancku
