### ISSUE TITLE
Latest strapi and latest schemas-to-plugins (as of 2023-11-17) using typescript fails with Cannot find module './dist/server'

### ISSUE THREAD

**Issue by briankandersen** [mancku/strapi-plugin-schemas-to-ts#37]
To replicate the error, just install the latest version of strapi. I selected TypeScript and Postgresql. I added this to package.json

"strapi-plugin-schemas-to-ts": "https://github.com/mancku/strapi-plugin-schemas-to-ts.git"

And then I did an npm install, and an npm run develop. Please see attached screenshot

![strapi error](https://github.com/mancku/strapi-plugin-schemas-to-ts/assets/32012293/6e53fae0-3605-41de-a18a-a903b28805e7)

P.S. It also fails when using strapi quick install

**Comment by mancku** [comment]
Hi @briankandersen  I just released the 1.1.20 version of the plugin that fixes that

**Comment by briankandersen** [comment]
Hi Mancku,

Thank you 😊

Med venlig hilsen / Yours sincerely,
______________________________
Brian Kjærsgaard Andersen
Digitalization Engineer
Tel +45 99806522 Mob +45 21470928
***@***.******@***.***>

***@***.***
Technology Centre Skjern (TC-Skjern)
Stålvej 7 DK-6900 Skjern
Tel +45 97353511  Fax +45 99806260
www.velux.com<http://www.velux.com/>
ü Please consider the environment before printing this e-mail!
