### ISSUE TITLE
Content types missing `createdAt`, `updatedAt` and `publishedAt` attributes

### ISSUE THREAD

**Issue by SeedyROM** [mancku/strapi-plugin-schemas-to-ts#4]
Let me know if I can I can help!

**Comment by mancku** [comment]
Hi @SeedyROM thank you for letting me know about this one! 
I've already fixed it, and I'm doing some tests before committing & pushing the code, so I don't need help this time, but it is much appreciated that you offered it! :)

**Comment by mancku** [comment]
Hi @SeedyROM I just published the 1.1.1 version with this fix and also the one you made in https://github.com/mancku/strapi-plugin-schemas-to-ts/pull/3
