### ISSUE TITLE
Able to write types to specific file

### ISSUE THREAD

**Issue by Justin-van-der-Velden** [mancku/strapi-plugin-schemas-to-ts#44]
Hello,

Is it able to write all types into on file or else write alle the `ts` file into one specific folder?

**Comment by mancku** [comment]
Hi @Justin-van-der-Velden I'm trying to address that one in here: https://github.com/mancku/strapi-plugin-schemas-to-ts/issues/22

**Comment by mancku** [comment]
@Justin-van-der-Velden It has been done in https://github.com/mancku/strapi-plugin-schemas-to-ts/pull/50 and published in version 1.3.0
