### ISSUE TITLE
How to remove all generated types?

### ISSUE THREAD

**Issue by gregg-cbs** [mancku/strapi-plugin-schemas-to-ts#45]
I have just installed this plugin. If I want to remove/uninstall it from my project does it remove all the types it generated? Any chance of an option that does remove all the generated types?

Thanks!

**Comment by mancku** [comment]
Hi @gregg-cbs removing the plugin won't remove the generated files.
As per your second question, I'm working in a way to remove all generated types from within the plugin itself

**Comment by gregg-cbs** [comment]
Amazing! Thank you.

**Comment by mancku** [comment]
Hi @gregg-cbs I just published version 1.2.0, which includes this fix

**Comment by gregg-cbs** [comment]
You are on fire!! Keep up the good work.

**Comment by mancku** [comment]
Thanks @gregg-cbs I got some bank holidays and I'm trying to publish some of the historic issues and petitions for the plugin :)
