### ISSUE TITLE
User: missing fields

### ISSUE THREAD

**Issue by gregg-cbs** [mancku/strapi-plugin-schemas-to-ts#46]
This plugin generates a user.ts file in 'common/shemas-to-ts' -> which user is this? Admin user or User Permissions user?

The types seem to be missing fields like "password" and any other custom fields added to the user schema including relational fields.

Generated Types
![image](https://github.com/mancku/strapi-plugin-schemas-to-ts/assets/57114335/0838cbbc-e9af-46dc-89d8-d4c857f13c87)

Schema
![image](https://github.com/mancku/strapi-plugin-schemas-to-ts/assets/57114335/9c1273c3-1b98-44c6-9a24-a9632a512e63)

Thanks!

**Comment by mancku** [comment]
Hi @gregg-cbs it's the Permissions User, as the Admin User is not part of the Content Types

**Comment by gregg-cbs** [comment]
Appreciate the response. This has the chance to be a great plugin for the community. Im hoping there will not be a need for it in the future and that strapi sorts their typing out.
