### ISSUE TITLE
Dev server will not run if the types folder does not exist and files are referencing types

### ISSUE THREAD

**Issue by gregg-cbs** [mancku/strapi-plugin-schemas-to-ts#52]
Not sure how we would get around this one but if the generated types folder does not exist (has been deleted) then the dev server will not run because the types are only generated after the dev server tries to reference them in files.

**Comment by mancku** [comment]
@gregg-cbs Not 100% sure if I understood the issue, but you can try and delete/create them using the CLI, then run Strapi again without problems

**Comment by gregg-cbs** [comment]
Yes you understood. CLI Documentation for future reference:
https://github.com/mancku/strapi-plugin-schemas-to-ts?tab=readme-ov-file#generate-interfaces-command-name-generateinterfaces
